### ISSUE TITLE
Question: why dose the extra declarations are needed? 

### ISSUE THREAD

**Issue by Bnaya** [mrmckeb/typescript-plugin-css-modules#11]
I'm just wondering why the 
```ts
declare module '*.module.css' {
  const classes: { [key: string]: string };
  export default classes;
}

declare module '*.module.scss' {
  const classes: { [key: string]: string };
  export default classes;
}

declare module '*.module.sass' {
  const classes: { [key: string]: string };
  export default classes;
}```

Decelerations are needed, if the service populate them itself

Thanks :)

**Comment by mrmckeb** [comment]
Good question :) You'll find that during build, they're needed. TypeScript currently doesn't use plugins during build... sadly.

If you'r finding that this is not the case, please let me know! Note that these are included in `create-react-app`/`react-scripts` already.

**Comment by Bnaya** [comment]
So i guess, we can make maybe create real interfaces using the information inside the service?

**Comment by mrmckeb** [comment]
So, the plugin creates the type information in real-time, but unfortunately Microsoft hasn't committed to any way to make this work in build. So you have the option to add `.d.ts` files... but that clutter in your folders seems less than ideal.

https://github.com/Microsoft/TypeScript/issues/16607

**Comment by Finesse** [comment]
Do plugins work when I run `tsc --noEmit` on TypeScript 3.5?

**Comment by mrmckeb** [comment]
Hi @Finesse, unfortunately Microsoft hasn't allowed this yet. This issue is still outstanding...
https://github.com/microsoft/TypeScript/issues/16607

As for your issue around the plugin not working, in VSCode I use it myself and it's working fine with Less and Sass CSS modules. Can you share any more information?

In VSCode, I recommend the first approach, as you can use options: https://github.com/mrmckeb/typescript-plugin-css-modules#visual-studio-code
