### ISSUE TITLE
Regular importing the scss files not working

### ISSUE THREAD

**Issue by KoichaDev** [mrmckeb/typescript-plugin-css-modules#147]
I am having a bug that if you wish to use

`import './button.module.scss';` is not working

The only thing that is working is:

`import styles from './button.module.scss';`

Any idea how to fix this?

**Comment by xeho91** [comment]
Nothing to fix here, the first example is incorrect usage of CSS modules.

**Comment by KoichaDev** [comment]
@xeho91 How am I using it wrong?

**Comment by Bjorn-Eric-Abr** [comment]
> @xeho91 How am I using it wrong?

The examples you provided are two different types of imports.

You want to use 
`import styles from './button.module.scss';` so that you can reference `styles` when adding class from that module to a component like `className={styles.button}`.

What I think can confuse this a bit is that in e. g. Create React App, Webpack is configured to handle all sorts of imports, like `.css` or `.sccs` [if you tweak it a bit](https://www.better.dev/adding-sass-to-create-react-app). This also goes for images, other JSX files and so on. This will tell Webpack to include it as an asset in the final bundle.

**Comment by mrmckeb** [comment]
That's correct, this plugin provides IDE types for object imports - not unassigned imports, sorry!

Thanks for helping to explain @Bjorn-Eric-Abr!
