### ISSUE TITLE
Extended failure of #66

### ISSUE THREAD

**Issue by nokternol** [mrmckeb/typescript-plugin-css-modules#70]
**Describe the bug**
node module resolution fails when starting with ~ and the import steps are more than 1
Edge case of #66 

**To Reproduce**
Forked version of the repo used for #66
https://github.com/nokternol/typescript-plugin-css-modules-issues-66.git
App.tsx does not render it's types correctly due to the ts failing in getClasses line 80

**Expected behavior**
Able to resolve the modules imported further up the hierarchy.

**Screenshots**
![image](https://user-images.githubusercontent.com/16777127/71264925-0d386b80-233d-11ea-9e24-2d97865da59f.png)

**Desktop (please complete the following information):**

- OS: Win 10
- Browser Chrome 79
- Version 2.1.2
- IDE VSCode

**Additional context**
As a workaround, you can go straight to the source (Fix from #66) but this may not work for all situations.
We have a top-level variables which holds our and imported framework variables that the app can then reference but in this case the plugin fails with the same error this issue was raised for.

**Comment by mrmckeb** [comment]
I'm sorry @nokternol, I've been out of action for a bit (Christmas).

I'm using bootstrap in the examples, but wasn't importing like this. There seems to be an issue here:
https://github.com/mrmckeb/typescript-plugin-css-modules/pull/69/files#diff-5ae41b718c24e67dcdf377fdeb0b939aR61-R64

I assume this is because I didn't cater for nested imports... I'll take a look tomorrow and work out a fix. 

I hope this didn't cause you too much pain over the last week.

**Comment by mrmckeb** [comment]
Hi @nokternol, if you remove the `~`, you should find that the import works - can you let me know if that works for you? That worked when testing locally.

Again, this is an issue with the parser itself from what I can see, and I'll ask them for support on the issue to see if we can find a proper fix.

**Comment by nokternol** [comment]
@mrmckeb Apologies for the slow response.
This does appear to work. By removing the tilde from the front of the package name the nested import succeeds. 
Strangely though if I import the interim file with "../variables" instead of "../variables.scss" it still fails.
But there is a way to make it all work so I am happy. Thank you for checking into it for me.

**Comment by mrmckeb** [comment]
No problem, I'll leave the issue open for now and look for a better solution. It's hard to get this right as we need to use a Sass processor that supports a sync API - TypeScript doesn't support async operations.

**Comment by erwin-k** [comment]
I've got this issue with Less aswell, unfortunately removing ~ does not work in Less.

**Comment by mrmckeb** [comment]
Hi @erwin-k, have you tried passing through options to the less loader? 

You can pass through paths ([detailed here](http://lesscss.org/usage/#less-options)) to our `rendererOptions` ([details here](https://github.com/mrmckeb/typescript-plugin-css-modules#rendererOptions)).

If that works, let me know and I can update the implementation internally so that it includes `node_modules` by default. 

If it doesn't work, please raise a new issue so we can track it separately - as it's unrelated to the issue in this thread :)

**Comment by mrmckeb** [comment]
I'll close this off as there hasn't been a response recently, but do feel free to reopen if the issue persists.

**Comment by irrvrsl** [comment]
> I've got this issue with Less aswell, unfortunately removing ~ does not work in Less.

Hello, @mrmckeb ! I have this issue as well. I've tried with your advice to include path in "paths", but typescript still complains. Please checkout screenshots below. Perhaps I've missed something. Thanks!

![image](https://user-images.githubusercontent.com/10095366/85777436-71504800-b743-11ea-865a-658a08a36ccf.png)

![image](https://user-images.githubusercontent.com/10095366/85778124-10753f80-b744-11ea-9741-2ffc8ddbbc2c.png)

**Comment by dcapo** [comment]
Is there any new guidance on how to handle this? I'm running into the same issue but the nested import is made by an npm dependency, so I can't simply remove the tilde.

**Comment by mrmckeb** [comment]
@dcapo it's a tricky one, because this plugin actually hands all of that work over to the appropriate renderer (Sass, Less, etc.), meaning that there's no opportunity to modify anything other than the imported file.

One of our contributors built this, maybe it will help? It provides a custom renderer to this plugin, that should resolve imports like this.
https://github.com/dancon/less-plugin-aliases
