### ISSUE TITLE
tslint complains about not using default exported name

### ISSUE THREAD

**Issue by zanona** [mrmckeb/typescript-plugin-css-modules#85]
I use `typescript-tslint-plugin` and I am trying to import my modules as `styles` as follow:

```ts
import styles from './styles/main.module.less';
```

However, tslint complains with: 

    Expected import 'styles' to match the default export 'classes'. (match-default-export-name)

I think that's strange because my `styles/index.d.ts` files has the below, which doesn't seem to be taken into consideration.

```ts
declare module '*.module.less' {
  const styles: { [key: string]: string };
  export default styles;
}
```

I also tried the `customTemplate.js` plugin option with the following

```js
module.exports = (dts, { classes, logger }) => {
  return [
    dts,
    'export const __cssModule: true;',
    `export type styles = '${Object.keys(classes).join("' | '")}';`,
  ].join('\n');
};
```

But that also didn't have any effect.

What's the best way to have the declarations default exporting either anonymously or named as `styles`?

Thanks in advance

**Comment by mrmckeb** [comment]
Hi @zanona, thanks for raising this.

I assume the issue is that you are adding the `dts` to your template... can you try removing it, or modifying it? It would still include `classes`.

Also, I would recommend moving away from TSLint, as it is deprecated (see: https://github.com/palantir/tslint/blob/master/README.md). ESLint works really well with TS - I use it on all of my projects, including this one!

**Comment by zanona** [comment]
Thanks for much for the suggestion, @mrmckeb.
It has worked with the following, indeed.

```js
module.exports = (dts, {classes}) => {
  const props = Object.keys(classes).map(c => `${c}:string`).join(';');
  return `declare const styles: { ${props} }; export default styles;`;
};
```
