### ISSUE TITLE
Guidance re: command-line usage?

### ISSUE THREAD

**Issue by jrr** [mrmckeb/typescript-plugin-css-modules#90]
I understand that typescript-plugin-css-modules is a _language service_ plugin that can't take effect at tsc compile time. The VS Code experience is great, but limited in that it's only able to show me squiggles in open files.

What I'd really like is, some way to analyze _all my code_ in one go from the command line, so I could do this in CI in lieu of checking at tsc time.

Is there some way to invoke the language service from the command line? Can you point me somewhere to look for such a thing? I started [here](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin), but haven't gotten very far.

If there's a decent way to do this, it might be worth citing in the Readme for other folks who'd like to automate the check.

**Comment by mrmckeb** [comment]
Hi @jrr, I know this is possible, but I personally didn't go down this path.

There is a project called [`ttypescript`](https://github.com/cevek/ttypescript) that has a concept of transforms, but the CSS modules support they have is limited ([reference](https://github.com/longlho/ts-transform-css-modules)).

Another option is to use one of loaders ([example](https://www.npmjs.com/package/typings-for-css-modules-loader)) that adds *.d.ts files for all of your CSS files, but that clutters your directories.

Finally, I know it is possible to wrap TypeScript in a custom transformer... but I've never tried that. There is an example in this article, with links below: https://levelup.gitconnected.com/writing-a-custom-typescript-ast-transformer-731e2b0b66e6

Again, I would love to have this supported - but for the projects where I use CSS modules, I don't personally think the complexity/effort of the above options make the above viable (for me).

Let me know if I can help with anything else!

**Comment by nirtamir2** [comment]
I use `typescript-plugin-css-modules` and it works well. I notice a problem when I have a pre-commit hook that runs `tsc`, and I also have the `noPropertyAccessFromIndexSignature` property in `tsconfig.json` - my commit hook fail (because it does not generate the TypeScript definitions in this case). I wonder if there is a HACK to keep this flag and understand the typescript definitions / ignore css modules type checking (my TypeScript service does it "good enough"). Currently, I removed this flag temporary, but I wonder if there is a good solution
